# Generated by Django 6.1 on 2026-08-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文件名称')),
                ('file', models.FileField(upload_to='downloads/', verbose_name='文件')),
                ('description', models.TextField(blank=True, verbose_name='文件说明')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='上传日期')),
            ],
        ),
    ]
