# Generated by Django 6.1 on 2026-08-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_age_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('category', models.CharField(choices=[('school', '学校新闻'), ('activity', '校园活动'), ('education', '教育教学'), ('student', '学生动态'), ('notice', '通知公告')], default='school', max_length=20, verbose_name='新闻分类')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='新闻图片')),
                ('summary', models.TextField(blank=True, verbose_name='新闻摘要')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('publish_date', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ['-publish_date'],
            },
        ),
    ]
