# Generated by Django 6.1 on 2026-08-19 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
