# Generated by Django 6.1 on 2026-08-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='留言人')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
            ],
        ),
    ]
